version: "3"

services:
  db:
    image: postgres:12  
    container_name: db  
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./temp:/var/lib/postgres
    restart: always